---
version: '3.3' 
services:
  redistools:
    build: .
    command: ["bash"]
  lint:
    build: .
    image: python:3-alpine
    command: ["./bin/lint"]
  redis:
    command: redis-server --dbfilename 'redis.rdb'
    image: redis:3-alpine
    volumes: 
      - ./redis/:/data
    ports:
      - 6379:6379 
